version: '3'
services:
  app:
    image: your-image-name:tag  # Use the image name and tag from your Dockerfile
    ports:
      - "8080:8080"  # Map port 8080 from the container to your host
    depends_on:
      - redis  # Ensure that the 'redis' service is started before 'app'

  redis:
    image: redis:latest  # Use the official Redis image
    ports:
      - "6379:6379"  # Map Redis default port